#!/bin/bash

# Make sure, serial port is configured correctly
/opt/hifiberry/bin/enable-updi

# Flash firmware
i2cset -y -f 1 0x77 0x0e 0 # disable interrupt pin for programming
systemctl stop audiocontrol2
pymcuprog  -t uart -d atmega808 -u /dev/ttyAMA0  --uart-timeout 2 -f /opt/hifiberry/powercontroller/firmware-r*.hex --erase --verify write
systemctl start audiocontrol2
