#!/bin/sh
DEVICE=/dev/mmcblk0

FSTABDATA=`cat /etc/fstab | grep /data`
if [ "$FSTABDATA" == "" ]; then
 echo "No filesystem defined in /etc/fstab, creating file system"
 mkfs -t f2fs ${DEVICE}p4
fi

DATA=`mount | grep data`
if [ "$DATA" == "" ]; then
 echo "/data not mounted, trying to mount it"

 if [ ! -d /data ]; then
  echo "/data does not exist, creating it"
  mkdir /data
 fi

 mount ${DEVICE}p4 /data
 if [ "$?" != "0" ]; then
  echo "Could not mount /data, trying to create a new file system"
  exit 1
 fi

 echo "adding /data to fstab"
 cat /etc/fstab | grep -v ${DEVICE}p4 > /tmp/fstab
 echo "${DEVICE}p4    /data    auto    defaults,nofail    0    2" >>/tmp/fstab
 mv /etc/fstab /etc/fstab.bak
 mv /tmp/fstab /etc/fstab

fi

if [ -d /library ]; then
 if [ ! -d /data/library ]; then
  mv /library /data
 else
  echo "/data/library already exists, will use this one"
  mv /library /library.bak
 fi
fi

ln -s /data/library /library

echo "disabling systemd service, this is a one-time job"
systemctl disable activate-data-partition.service

