#!/bin/bash

SHAIRPORT=`ps -ef | grep shairport | grep -v grep | awk '{print $1}'`
SQUEEZELITE=`ps -ef | grep squeezelite | grep -v grep | awk '{print $1}'`
SPOTIFYD=`ps -ef | grep spotifyd | grep -v grep | awk '{print $1}'`
DSPTOOLKIT=`ps -ef | grep sigmatcpserver | grep -v grep | awk '{print $1}'`
BLUETOOTHD=`ps -ef | grep bluetoothd | grep -v grep | awk '{print $1}'`
MPD=`ps -ef | grep mpd | grep -v grep | awk '{print $1}'`

echo "dsptoolkit:     " $DSPTOOLKIT
echo "shairport:      " $SHAIRPORT
echo "spotifyd:       " $SPOTIFYD
echo "squeezelite:    " $SQUEEZELITE
echo "bluetoothd:     " $BLUETOOTHD
echo "mpd:            " $MPD

