#!/bin/bash
. /etc/hifiberry.state

function check_systemd {
 echo -n "$1: "
 systemctl is-active $2 1>/dev/null
 if [ $? == 0 ]; then
   echo running
 else
   echo not running
 fi
}

echo -n "HiFiBerryOS version: "
cat /etc/hifiberry.version

echo "Pi model: $CURRENT_PIMODEL"
echo "Sound card: $CURRENT_CARD"
echo "Sound card ID: $CURRENT_HW_SHORT"
echo "Mixer: $CURRENT_MIXER_CONTROL"
echo "Features: $CURRENT_FEATURES"

echo -n "Linux version: "
uname -a

echo -n "/data mounted: "
M=`mount | grep " /data "`
if [ "$M" == "" ]; then
  echo FAIL
else
  echo OK
fi 

echo -n "/dev/dri/card0: "
if [ -c /dev/dri/card0 ]; then 
  echo OK
else
  echo NO
fi

echo -n "BT devices: "
DEV=""
for INT in `hciconfig | grep hci | awk -F: '{print $1}'`; do
 MANUFACTURER=`hciconfig -a $INT | grep "Manufacturer:" | awk -F: '{print $2}'`
 DEV="$DEV $INT - $MANUFACTURER,"
done 
echo $DEV | sed s/,\$//

echo -n "WiFi devices: "
DEV=""
for INT in `iwconfig 2>/dev/null | grep wlan | awk '{print $1}'`; do 
 DEV="$DEV $INT,"
done
echo $DEV | sed s/,\$//

# Daemons
for i in audiocontrol2 beocreate2 bluetooth bluealsa bluealsa-aplay dlnampris mpd mpd-mpris pigpiod raat shairport-sync sigmatcp snapcastmpris spotify squeezelite sshd ympd weston cog; do
 check_systemd $i $i.service
done
