#!/bin/bash

# On the Pi Zero, volume controls won't show up before playing something :(
SOFTVOL=`amixer | grep Softvol`
if [ "$SOFTVOL" == "" ]; then
 play -n synth 1 sine 1
fi

FOUND=`aplay -l|grep hifiberry | grep -v "pcm5102"`
CONFIG=/boot/config.txt
REBOOTFILE=/tmp/reboot

function exit_and_cleanup() {
	sync
	mount -o ro,remount /boot
	exit
}

function check_i2c {
	modprobe i2c-dev
        if [ ! -e /dev/i2c-1 ]; then
                echo "I2C device file not found, need to modify config.txt"
                echo "dtparam=i2c1=on" >> $CONFIG
                echo "Enabling I2C" >> $REBOOTFILE
        fi
}

function check_hat {
	if [ -f /proc/device-tree/hat/product ]; then
		HATCARD=`cat /proc/device-tree/hat/product`
	else
		HATCARD=""
	fi
}

function detect_card {
	check_hat()

	if [ "$HATCARD" == "DAC+ ADC Pro" ]; then
		echo "dacplusadcpro"
		return
	fi

	if [ "$HATCARD" == "DAC+ ADC" ]; then
                echo "dacplusadc"
                return
        fi

	if [ "$HATCARD" == "DAC 2 HD" ]; then
		echo "dac2hd"
		return
	fi

        # DAC+ ADC Pro
        res=`i2cget -y 1 0x4a 25 2>/dev/null`
        if [ "$res" == "0x07" ]; then
                echo "dacplusadcpro"
		return
        fi

	# Digi/Digi+
	res=`i2cget -y 1 0x3b 1 2>/dev/null`
	if [ "$res" == "0x88" ]; then
		echo "digi"
		return
	fi

	# DAC Plus
	res=`i2cget -y 1 0x4d 40 2>/dev/null`
	if [ "$res" == "0x02" ]; then
                echo "dacplus"
		return
        fi

	# Amp/Amp+
	res=`i2cget -y 1 0x1b 0 2>/dev/null`
        if [ "$res" == "0x6c" ]; then
                echo "amp"
		return
        fi
        if [ "$res" == "0x60" ]; then
                echo "amp"
		return
        fi

	# DAC 2 HD
	res=`i2cget -yf 1 0x62 17 2>/dev/null`
	if [ "$res" == "0x8c" ]; then
		echo "dachd"
		return
	fi

        # Beocreate
        res=`i2cget -y 1 0x60 2 2>/dev/null`
        if [ "$res" == "0x03" ]; then
                echo "beo"
		return
        fi

        # Some I2C addresses might be blocked from HAT EEPROM, but hifibarry-dac is used
        res=`i2cdetect -y 1 | grep UU`
        if [ "$res" != "" ]; then
                echo "blocked"
        fi
}

FORCEEEPROM=`cat /boot/config.txt | grep force_eeprom_read`
if [ "$FORCEEEPROM" != "" ]; then
	echo "Detected force_eeprom_read, removing it" >> /var/log/hifiberry.log
	mount -o remount,rw /boot
	cat /boot/config.txt | grep -v force_eeprom_read > /tmp/config.txt
	cp /boot/config.txt /boot/config.txt.bak
	cp /tmp/config.txt /boot/config.txt
	sync
fi

if [ "$FOUND" == "" ]; then
	echo "No HiFiBerry card configured, try to probe using I2C" >> /var/log/hifiberry.log

	echo "Mounting /boot"
	mount -o remount,rw /boot
	if [ ! -f /boot/config.txt ]; then
		echo "couldn't mount FAT file system, aborting card detection" >> /var/log/hifiberry.log
   		exit 1
 	fi

	echo "Detecting using I2C" 
	check_i2c
	card=$(detect_card)

	if [ "$card" == "beo" ]; then
		echo "Detected Beocreate"
		FOUND2=`aplay -l|grep hifiberry`
		if [ "$FOUND2" != "" ]; then
			exit_and_cleanup
		fi
		card=dac
	fi

	if [ "card" == "blocked" ]; then
		FOUND2=`aplay -l|grep hifiberry-dac`
		if [ "$FOUND2" != "" ]; then
			echo "HiFiBerry DAC driver used, but some card might be configured using HAT EEPROM"
			cat /boot/config.txt | grep -v "hifiberry-dac" > /boot/config.txt2
			diff /boot/config.txt /boot/config.txt2
			if [ "$?" != 0 ]; then
				echo "Found HiFiBerry DAC configuration, removing it" >>/var/log/hifiberry.log
				mv /boot/config.txt2 /boot/config.txt
				echo "Removing hifiberry-dac overlay" >> $REBOOTFILE
			fi

		fi
	fi

	if [ "$card" != "" ]; then
		echo "Detected $card" >>/var/log/hifiberry.log
		echo "Creating new config.txt" >>/var/log/hifiberry.log
		cat $CONFIG | grep -v "hifiberry" > /tmp/config.txt 
		echo "dtoverlay=hifiberry-$card" >> /tmp/config.txt
		mv /tmp/config.txt $CONFIG
		echo "Adding $card to config.txt" >> $REBOOTFILE
	else
		echo "Could not find an I2C enabled sound card"
		cat /boot/config.txt | grep -v "hifiberry-digi" | grep -v "hifiberry-amp" | grep -v "hifiberry-dacplus" > /boot/config.txt2
		diff /boot/config.txt /boot/config.txt2
		if [ "$?" != 0 ]; then
			echo "Found old configuration, removing it" >>/var/log/hifiberry.log
			mv /boot/config.txt2 /boot/config.txt
			echo "Removing old configuration in config.txt" >> $REBOOTFILE
		fi
		echo "Assuming HiFiBerry DAC+ Light, Zero"
		FOUND2=`aplay -l|grep hifiberry`
		if [ "$FOUND2" != "" ]; then
			exit_and_cleanup
		else
			echo "dtoverlay=hifiberry-dac" >> /boot/config.txt
			echo "Nothing detected, assuming HiFiBerry DAC+ Light/Zero" >>/var/log/hifiberry.log
			echo "Enabling DAC+ Light" >> $REBOOTFILE
		fi
	fi
else
   echo "Found HiFiBerry card: $FOUND" >>/var/log/hifiberry.log
fi

exit_and_cleanup
