#!/bin/bash

FOUND=`aplay -l|grep hifiberry | grep -v "pcm5102"`
VERSION=2
CONFIG=/boot/config.txt

function check_i2c {
	modprobe i2c-dev
        if [ ! -e /dev/i2c-1 ]; then
                echo "I2C device file not found, need to modify config.txt"
                echo "dtparam=i2c1=on" >> $CONFIG
                echo "Rebooting in 5 seconds, abort reboot?"
                read -t 5 abort
                if [ "$abort" == "" ]; then
                        sync
                        reboot
                fi
        fi
}

function detect_card {
	# Digi/Digi+
	res=`i2cget -y 1 0x3b 1 2>/dev/null`
	if [ "$res" == "0x88" ]; then
		echo "digi"
	fi

	# DAC Plus
	res=`i2cget -y 1 0x4d 40 2>/dev/null`
	if [ "$res" == "0x02" ]; then
                echo "dacplus"
        fi

	# Amp/Amp+
	res=`i2cget -y 1 0x1b 0 2>/dev/null`
        if [ "$res" == "0x6c" ]; then
                echo "amp"
        fi
        if [ "$res" == "0x60" ]; then
                echo "amp"
        fi

        # Beocreate
        res=`i2cget -y 1 0x60 2 2>/dev/null`
        if [ "$res" == "0x03" ]; then
                echo "beo"
        fi

        # Some I2C addresses might be blocked from HAT EEPROM, but hifibarry-dac is used
        res=`i2cdetect -y 1 | grep UU`
        if [ "$res" != "" ]; then
                echo "blocked"
        fi
}

if [ "$FOUND" == "" ]; then
 echo "No HiFiBerry card configured, try to probe using I2C" >> /var/log/hifiberry.log

 echo "Detecting using I2C" 
 check_i2c
 card=$(detect_card)

 if [ "$card" == "beo" ]; then
   echo "Detected Beocreate"
   FOUND2=`aplay -l|grep hifiberry`
   if [ "$FOUND2" != "" ]; then
       exit 0
   fi
   card=dac
 fi

 if [ "card" == "blocked" ]; then
   FOUND2=`aplay -l|grep hifiberry-dac`
   if [ "$FOUND2" != "" ]; then
       echo "HiFiBerry DAC driver used, but some card might be configured using HAT EEPROM"
       cat /boot/config.txt | grep -v "hifiberry-dac" > /boot/config.txt2
        diff /boot/config.txt /boot/config.txt2
        if [ "$?" != 0 ]; then
          echo "Found HiFiBerry DAC configuration, removing it" >>/var/log/hifiberry.log
          mv /boot/config.txt2 /boot/config.txt
          sleep 5
          sync
          reboot
        fi

   fi
 fi

 if [ "$card" != "" ]; then
 	echo "Detected $card" >>/var/log/hifiberry.log
	echo "Creating new config.txt" >>/var/log/hifiberry.log
	cat $CONFIG | grep -v "hifiberry" > /tmp/config.txt 
	echo "dtoverlay=hifiberry-$card" >> /tmp/config.txt
	mv /tmp/config.txt $CONFIG
	echo "Rebooting in 5 seconds, abort reboot?"
	read -t 5 abort
	if [ "$abort" == "" ]; then
		sync
		reboot
	fi
 else
	echo "Could not find an I2C enabled sound card"
        cat /boot/config.txt | grep -v "hifiberry-digi" | grep -v "hifiberry-amp" | grep -v "hifiberry-dacplus" > /boot/config.txt2
        diff /boot/config.txt /boot/config.txt2
        if [ "$?" != 0 ]; then
          echo "Found old configuration, removing it" >>/var/log/hifiberry.log
          mv /boot/config.txt2 /boot/config.txt
          sleep 5
          sync
          reboot
        fi
        echo "Assuming HiFiBerry DAC+ Light, Zero"
        FOUND2=`aplay -l|grep hifiberry`
        if [ "$FOUND2" != "" ]; then
          exit 0
        else
          echo "dtoverlay=hifiberry-dac" >> /boot/config.txt
          echo "Nothing detected, assuming HiFiBerry DAC+ Light/Zero" >>/var/log/hifiberry.log
          sleep 5
          reboot
        fi
 fi
else
   echo "Found HiFiBerry card: $FOUND" >>/var/log/hifiberry.log
fi

