#!/bin/sh
if [ -f /tmp/fix-volume.done ]
 exit
fi
. /etc/hifiberry.state
for MIXER in Softvol DSPVolume; do
  if [ "$CURRENT_MIXER_CONTROL" != "$MIXER" ]; then
    amixer sset "$MIXER" 100%
  fi
done
touch /tmp/fix-volume.done
