#!/bin/bash

# try to directly access the HAT via /sys
if [ -f /proc/device-tree/hat/product ]; then
  PRODUCT=$(tr -d '\0' </proc/device-tree/hat/product)
  VENDOR=$(tr -d '\0' </proc/device-tree/hat/vendor)
  UUID=$(tr -d '\0' </proc/device-tree/hat/uuid)
else
  EEPFILE=/tmp/eeprom.eep
  TXTFILE=/tmp/eeprom.txt

  modprobe i2c_dev
  modprobe at24

  # Bus number is not fixed, correct I2C adapter is iden
  for i in $(seq 1 30); do
    if [ -d /sys/class/i2c-adapter/i2c-$i ]; then
      I2C=`ls -l /sys/class/i2c-adapter/i2c-$i | grep "platform/ffff"`
      if [ "$I2C" != "" ]; then
        DEVID=$i
        break
      fi
    fi
  done

  if [ ! -d "/sys/class/i2c-adapter/i2c-$DEVID/$DEVID-0050" ]; then
    echo "24c32 0x50" > /sys/class/i2c-adapter/i2c-$DEVID/new_device
  fi

  if [ ! -d "/sys/class/i2c-adapter/i2c-$DEVID/$DEVID-0053" ]; then
    echo "24c32 0x53" > /sys/class/i2c-adapter/i2c-$DEVID/new_device
  fi

  if [ -f "/sys/class/i2c-adapter/i2c-$DEVID/$DEVID-0050/eeprom" ]; then
    dd if=/sys/class/i2c-adapter/i2c-$DEVID/$DEVID-0050/eeprom of=$EEPFILE 2>/dev/null
  else
    dd if=/sys/class/i2c-adapter/i2c-$DEVID/$DEVID-0053/eeprom of=$EEPFILE 2>/dev/null
  fi
  
  /usr/bin/eepdump $EEPFILE $TXTFILE >/dev/null
  if [ -f $TXTFILE ]; then 
    VENDOR=`cat $TXTFILE | grep "vendor " | awk -F\" '{print $2}' | xargs echo`
    PRODUCT=`cat $TXTFILE | grep "product " | awk -F\" '{print $2}' | xargs echo`
    UUID=`cat $TXTFILE | grep "product_uuid " | awk '{print $2}' | xargs echo`

    if [ "$VENDOR" == "" ]; then
      VENDOR="no vendor"
    fi
    if [ "$PRODUCT" == "" ]; then
      PRODUCT="no product"
    fi
    if [ "$UUID" == "" ]; then
      UUID="unknown"
    fi
  fi
fi

if [ "$1" == "-a" ]; then
  echo $VENDOR:$PRODUCT:$UUID
else
  echo $VENDOR:$PRODUCT
fi
rm $TXTFILE 2>/dev/null
