#!/bin/bash

DEVICE=/dev/mmcblk0

if [ -f /resize-me.2 ]; then
 echo "Resizing file system on /dev/mmcblk0p2"
 resize2fs -p /dev/mmcblk0p2
 rm /resize-me.2
fi

if [ ! -f /resize-me ]; then
 echo "/resize-me does not exist, aborting"
 exit
fi

# Delete Partition 3
if [ -b ${DEVICE}p3 ]; then
INITIAL=1
fdisk $DEVICE <<EOT
d
3
w
EOT
partprobe
echo p | fdisk $DEVICE
fi

# Delete Partition 2
if [ -b ${DEVICE}p2 ]; then
fdisk $DEVICE <<EOT
d
2
w
EOT
partprobe
echo p | fdisk $DEVICE
fi

# Create partitions 2 and 3
fdisk $DEVICE <<EOT
n
p
2
65537
3065536
n
p
3
3065537
6065536
w
EOT
partprobe
echo p | fdisk $DEVICE

# Create partition 4
fdisk $DEVICE <<EOT
n
p


w
EOT
partprobe
echo p | fdisk $DEVICE

e2fsck -f -p $DEVICEp2

rm /resize-me
touch /resize-me.2

# Create fs in partition 4 if there is none
fsck.f2fs -p -f ${DEVICE}p4
RET=$?
if [[ $RET == 8 ] || [ $RET==255 ]] ; then
  mkfs -t f2fs /dev/mmcblk0p4
fi

echo "Resized partitions" >> /tmp/reboot
