#!/bin/bash

# Detect the device that's used for the root file system
DEVICEBASE=`mount | grep " / " | awk '{print $1}' | sed s/[0-9]\$//`
DEVICE=`echo $DEVICEBASE | sed s/p\$//`

if [ -f /resize-me.2 ]; then
 echo "Resizing file system on ${DEVICEBASE}2"
 resize2fs -p ${DEVICEBASE}2
 rm /resize-me.2
fi

if [ ! -f /resize-me ]; then
 echo "/resize-me does not exist, aborting"
 exit
fi

# Delete Partition 3
if [ -b ${DEVICEBASE}3 ]; then
INITIAL=1
fdisk $DEVICE <<EOT
d
3
w
EOT
partprobe
echo p | fdisk $DEVICE
fi

# Delete Partition 2
if [ -b ${DEVICE}2 ]; then
fdisk $DEVICE <<EOT
d
2
w
EOT
partprobe
echo p | fdisk $DEVICE
fi

# Create partitions 2 and 3
fdisk $DEVICE <<EOT
n
p
2
65537
3065536
n
p
3
3065537
6065536
w
EOT
partprobe
echo p | fdisk $DEVICE

# Create partition 4
fdisk $DEVICE <<EOT
n
p


w
EOT
partprobe
echo p | fdisk $DEVICE

e2fsck -f -p ${DEVICEBASE}2

rm /resize-me
touch /resize-me.2

# Create fs in partition 4 if there is none
fsck.f2fs -p -f ${DEVICEBASE}4
RET=$?
if [[ $RET == 8 || $RET==255 ]] ; then
  mkfs -t f2fs ${DEVICEBASE}4
fi

echo "Resized partitions" >> /tmp/reboot
