#!/bin/bash
if [ "$1" == "" ]; then 
 STORE=/etc/alsactl.store
else
 STORE=$1
fi

alsactl -f $STORE restore

dsptoolkit --timeout=5 set-volume `cat /etc/dspvolume.store`

. /etc/hifiberry.state
if [ "$CURRENT_MIXER_CONTROL" != "Softvol" ]; then
	amixer sset Softvol 100%
fi

if [ -f /opt/hifiberry/bin/fix-dacadcpro-mixer ]; then
        /opt/hifiberry/bin/fix-dacadcpro-mixer
fi
