#!/bin/bash
if [ "$1" == "" ]; then 
 STORE=/etc/alsactl.store
else
 STORE=$1
fi

alsactl -f $STORE restore

. /etc/hifiberry.state
if [ "$CURRENT_MIXER_CONTROL" != "Softvol" ]; then
	amixer sset Softvol 100%
fi
