#!/bin/sh
. /etc/roomeq.conf

if [ -f "$1" ]; then
 curl \
   --header "Content-Type: application/json" \
   --request POST \
   --data "@$1" \
   $ROOMEQURL/optimize
else
 curl \
   --header "Content-Type: application/json" \
   --request POST \
   --data "$1" \
   $ROOMEQURL/optimize
fi
