#!/bin/bash

cd `dirname $0`

if [ "$1" == "" ]; then
 	VERSION=`cat .piversion`
 	echo No version given, assuming Pi$VERSION
else
 	VERSION=$1
fi

echo $VERSION > .piversion

BRDIR=`./brdir $VERSION`

echo "Building in $BRDIR"
echo $VERSION > $BRDIR/.piversion
echo $VERSION > buildroot/PIVERSION

if [ "$VERSION" == "4" ]; then
	CFG="raspberrypi4_64_defconfig"
elif [ "$VERSION" == "3" ]; then
	CFG="raspberrypi3_64_defconfig"
else
	echo "Pi version $1 not supported"
	exit 1
fi

pushd ../buildroot
make $CFG
popd

mv ../buildroot/.config $BRDIR/.config
cat configs/override.conf >> $BRDIR/.config
echo "BR2_PACKAGE_PIVERSION_$VERSION=y" >> $BRDIR/.config
# use full package set
echo "BR2_PACKAGE_HIFIBERRY_ALL=y" >> $BRDIR/.config

# Update version
TS=`date +%Y%m%d`
echo $TS > buildroot/VERSION
