#!/bin/bash

BRDIR=../buildroot
echo "Fixing $BRDIR"

# Gstreamer has an incorrect dependency to Valgrind
#cat $BRDIR/package/gstreamer1/gstreamer1/gstreamer1.mk | grep -v BR2_PACKAGE_VALGRIND > $BRDIR/package/gstreamer1/gstreamer1/gstreamer1.mk.new
#mv  $BRDIR/package/gstreamer1/gstreamer1/gstreamer1.mk $BRDIR/package/gstreamer1/gstreamer1/gstreamer1.mk.orig
#mv  $BRDIR/package/gstreamer1/gstreamer1/gstreamer1.mk.new $BRDIR/package/gstreamer1/gstreamer1/gstreamer1.mk

# Patch rpi firmware to use newer version
if [ ! -f ../buildroot/package/rpi-firmware/rpi-firmware.mk.orig ]; then 
 cp ../buildroot/package/rpi-firmware/rpi-firmware.mk ../buildroot/package/rpi-firmware/rpi-firmware.mk.orig
 mv ../buildroot/package/rpi-firmware/rpi-firmware.hash ../buildroot/package/rpi-firmware/rpi-firmware.hash.orig
fi
sed -i s/RPI_FIRMWARE_VERSION.=.*/RPI_FIRMWARE_VERSION\ =\ 01ecfd2ba2b7cf3a2f4aa75ada895ee4a3e729f5/ ../buildroot/package/rpi-firmware/rpi-firmware.mk

# Patch 0w configuration
if [ ! -f ../buildroot/board/raspberrypi0w/genimage-raspberrypi0w.cfg.orig ]; then 
 cp ../buildroot/board/raspberrypi0w/genimage-raspberrypi0w.cfg ../buildroot/board/raspberrypi0w/genimage-raspberrypi0w.cfg.orig
fi 
sed -i s/bcm2708-rpi-0-w.dtb/bcm2708-rpi-zero-w.dtb/ ../buildroot/board/raspberrypi0w/genimage-raspberrypi0w.cfg 
