#!/bin/bash
TAG=2020.08
BRDIR=buildroot-${TAG}

cd `dirname $0`
cd ..

if [ -d $BRDIR ]; then
	echo "Saving current buildroot"
	rm -rf $BRDIR.bak
	mv $BRDIR $BRDIR.bak
fi

echo "Checking out buildoot tag ${TAG} from Github"
git clone https://github.com/buildroot/buildroot $BRDIR

echo "Checking out a known-good release"
pushd $BRDIR
git checkout $TAG

if [ -f ../hifiberry-os/buildroot/buildroot-${TAG}.patch ]; then
	echo "Applying patch"
	patch -p1 < ../hifiberry-os/buildroot/buildroot-${TAG}.patch
else	
	ls ../hifiberry-os/buildroot/buildroot-${TAG}.patch
	echo "No patch found - is this correct?"
fi
popd

echo "Symlinking to buildroot"
rm buildroot
ln -s $BRDIR buildroot

