#!/bin/bash
if [ "$1" == "" ]; then 
	TAG=2023.02.3
#        TAG=2021.11
else
	TAG=$1
fi

cd `dirname $0`

BRDIR=buildroot-${TAG}

cd `dirname $0`
cd ..

if [ -d $BRDIR ]; then
	echo "Saving current buildroot"
	rm -rf $BRDIR.bak
	mv $BRDIR $BRDIR.bak
fi

echo "Checking out buildoot tag ${TAG} from Github"
git clone https://github.com/buildroot/buildroot $BRDIR

echo "Checking out a known-good release"
pushd $BRDIR
git checkout $TAG

if [ -f ../hifiberry-os/buildroot/buildroot-${TAG}.patch ]; then
	echo "Applying patch"
	patch -p1 < ../hifiberry-os/buildroot/buildroot-${TAG}.patch
else	
	ls ../hifiberry-os/buildroot/buildroot-${TAG}.patch
	echo "No patch found - is this correct?"
fi
popd

#echo "Copying genimage configurations"
#cp -v hifiberry-os/buildroot/board/raspberrypi/genimage*cfg $BRDIR/board/raspberrypi

echo "Symlinking to buildroot"
rm buildroot
ln -s $BRDIR buildroot

