#!/bin/bash
cd `dirname $0`
cd ..
if [ -d buildroot ]; then
 echo "Saving exiting buildroot"
 mv buildroot buildroot.bak
fi

if [ -d buildroot-dev ]; then
 echo "Saving buildroot-dev"
 mv buildroot-dev buildroot-dev.bak
fi

echo "Checking out buildoot development tree"
git clone https://github.com/buildroot/buildroot buildroot-dev

echo "Checking out a known-good release"
pushd buildroot-dev
git checkout 197da6286612df9c0c1b5f41e307e1a9be780d0d

echo "Applying patch"
patch -p1 < ../hifiberry-os/buildroot/buildroot-dev.patch
popd

echo "Symlinking buildroot-dev"
ln -s buildroot-dev buildroot

