#!/bin/sh
sudo apt-get install git make gcc g++ unzip rsync bc sshpass zip ncurses-dev screen xsltproc libasound2-dev python python-pyalsa python3-pip gcc-multilib g++-multilib f2fs-tools
sudo python3 -m pip install hifiberrydsp
