#!/bin/sh
sudo apt-get install -y git make gcc g++ unzip rsync bc sshpass zip libncurses-dev screen xsltproc libasound2-dev python3 python3-pyalsa python3-pip gcc-multilib g++-multilib f2fs-tools avahi-utils
sudo python3 -m pip install hifiberrydsp
