#!/bin/bash
cd `dirname $0`

VERSION=$1

HOST=$2
if  [ "$HOST" == "" ]; then
 echo $0 version hostname
 echo  e.g. $0 3 10.0.1.23 will push the current Pi 3 release to the Pi with the IP address 10.0.1.23
 exit 1
fi 

PORT=$3
if [ "$PORT" == "" ]; then
 PORT=22
fi

./create-image $VERSION
IMG=`ls images/ | grep updater | grep pi$VERSION | tail -1`
echo "Updating $HOST with $IMG"
sshpass -p 'hifiberry' scp -P $PORT images/$IMG root@$HOST:/data/updater.tar.gz; 
sshpass -p 'hifiberry' ssh -p $PORT root@$HOST /opt/hifiberry/bin/extract-update --reboot


