# Hide MIDI devices from graph UIs
# This prevents most graph UIs from showing MIDI, but keeps them working.

monitor.alsa.rules = [
  {
    matches = [
      { media.class = "Midi/*" }
    ]
    actions = {
      update-props = {
        node.hidden = true
      }
    }
  }
]
