monitor.alsa.rules = [
  {
    matches = [
      {
        "media.class": "Stream/Output/Audio"
      }
    ]
    actions = {
      update-props = {
        "target.object": "effect_input.proc"
      }
    }
  }
]