#! /bin/sh

# Write profile to DSP DAC and play a test tone

OUT=/dev/tty1

case "$1" in
    start)
	echo "Programming DSP profile" > $OUT
	dsptoolkit install-profile /opt/hifiberry/contrib/dspaddon.xml > $OUT
	echo "Testing EEPROM programming" > $OUT
	dsptoolkit check-eeprom > $OUT
	echo "Playing test tone" > $OUT
	play -n synth 30 sine 1000 > $OUT
	echo "Done" > $OUT
	;;
    stop)
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

