#!/bin/sh
cd `dirname $0`
MYDIR=`pwd`

cd /tmp
mkdir shairport
cd shairport

if [ -f /etc/pacman.conf ]; then
 echo "Installing prerequisites using pacman"
 pacman -S --needed gcc openssl pkg-config avahi
else
 echo "Installing prerequisites using apt-get"
 sudo apt-get install -y git libao-dev libssl-dev libcrypt-openssl-rsa-perl libio-socket-inet6-perl libwww-perl avahi-utils libmodule-build-perl libasound2-dev libpulse-dev
fi

echo "Installing Net::SDP"
git clone https://github.com/njh/perl-net-sdp.git perl-net-sdp  
cd perl-net-sdp  
perl Build.PL 
sudo ./Build  
sudo ./Build test
sudo ./Build install
cd ..

echo "Retrieving shairport source"
git clone https://github.com/abrasive/shairport.git  
cd shairport
./configure
make -j 4
sudo make install -j 4

echo "Installing start scripts"
if [ -d /etc/init.d ]; then
 echo "Using old init script"
 sudo cp scripts/debian/init.d/shairport /etc/init.d/shairport
 sudo chmod a+x /etc/init.d/shairport
 udo update-rc.d shairport defaults
fi
if [ -d /etc/systemd ]; then
 echo "Using systemd"
 cd $MYDIR
 cp ../files/shairport.service /etc/systemd/system
 mkdir -p /etc/system.conf
 echo "Creating /etc/conf.d/shairport"
 cat <<EOT >/etc/conf.d/shairport
SHAIRPORT_ARGS="-o pulse -b 100"
EOT
 systemctl enable shairport
fi

echo "Adding user"
sudo useradd -g audio shairport

echo "Cleaning up"
#rm -rf /tmp/shairport
