#!/bin/sh
if [ -f /etc/pacman.conf ]; then
  echo "Installing basic tools using pacman"
  sudo pacman -S --needed alsa-lib alsa-utils mplayer
else
  echo "Installing basic tools using apt-get"
  sudo apt-get install -y alsa-lib alsa-utils mplayer
fi

