#!/bin/sh
VERSION=0.6
cd /tmp
mkdir alsaeq
cd alsaeq

echo "Installing prerequisites using apt-get"
sudo apt-get install caps libasound2-dev

echo "Retrieving alsaeq source"
wget http://www.thedigitalmachine.net/tools/alsaequal-$VERSION.tar.bz2
bunzip2 alsaequal-$VERSION.tar.bz2
tar xvf alsaequal-$VERSION.tar

echo "Compiling and installing alsaeq"
cd alsaequal
cat Makefile | sed s/usr\\/lib\\/alsa-lib/usr\\/lib\\/arm-linux-gnueabihf\\/alsa-lib/g > Makefile.new
mv Makefile Makefile.orig
mv Makefile.new Makefile
make -j 4
sudo make install -j 4


