#!/bin/sh
cd `dirname $0`
MYDIR=`pwd`

if [ -f /etc/pacman.conf ]; then
 echo "Installing prerequisites using pacman"
 pacman -S --needed gcc pkg-config git libmad faad2 mpg123
else
 # Some modules might be missing here
 echo "Installing prerequisites using apt-get"
 sudo apt-get install -y git libmad
fi

cd /tmp
mkdir squeezelite
cd squeezelite

echo "Retrieving squeezelite source"
git clone https://code.google.com/p/squeezelite/
cd squeezelite
make -j 4
sudo mkdir -p /usr/local/bin
sudo cp squeezelite /usr/local/bin

echo "Installing start scripts"
if [ -d /etc/init.d ]; then
 echo "Using old init script"
fi
if [ -d /etc/systemd ]; then
 echo "Using systemd"
 cd $MYDIR
 cp ../files/squeezelite.service /etc/systemd/system
 echo 'SQUEEZELITE_ARGS="-M HiFiBerry -o pulse"' > /etc/conf.d/squeezelite
 systemctl enable squeezelite
fi

echo "Adding user"

echo "Cleaning up"
rm -rf /tmp/squeezelite
