MAKEFLAGS=-j4

install:
	./cleanup-modules
	./install-basictools
	./install-pulseaudio
	./install-shairportsync
	./install-squeezelite
	./install-i2ctools
	./install-autoconfig

configure:
	./configure-network nat
