#!/bin/bash
cd `dirname $0`
. functions.bash

if [ "$1" == "nat" ]; then
	replace_line /etc/sysctl.conf net.ipv4.ip_forward net.ipv4.ip_forward=1
	sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
	sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
	sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
	sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
	replace_block /etc/network/interfaces IPTABLE "up iptables-restore < /etc/iptables.ipv4.nat"
elif [ "$1" == "bridge" ]; then
	echo
else
	echo "Mode $1 unknown"
	echo start with $0 nat\|bridge
fi
