#!/usr/bin/python
import subprocess
import re
import shutil

def get_docker_network_interfaces():
    # Get the list of network interfaces
    try:
        output = subprocess.check_output(['ip', '-o', 'link', 'show']).decode()
    except subprocess.CalledProcessError as e:
        print(f"Failed to get network interfaces: {e}")
        return ""
    
    # Filter Docker and bridge interfaces and create a comma-separated list
    ifaces = ",".join(re.findall(r': (br-|docker0[^:]*):', output))
    return ifaces.rstrip(',')

def update_avahi_configuration(ifaces):
    avahi_conf = "/etc/avahi/avahi-daemon.conf"
    avahi_conf_bak = "/tmp/avahi-daemon.conf.bak"
    
    # Create a backup of the Avahi configuration
    shutil.copy(avahi_conf, avahi_conf_bak)
    
    # Read the configuration, modify it, and write it back
    with open(avahi_conf, 'r') as file:
        lines = file.readlines()
  
    lines_changed = False  # Initialize a flag to track changes
    with open(avahi_conf, 'w') as file:
        for line in lines:
            if re.match(r'^#?deny-interfaces=', line):
                new_line = f"deny-interfaces={ifaces}\n"
                if line != new_line:  # Check if the line is actually different before writing
                    lines_changed = True
                file.write(new_line)
            else:
                file.write(line)
    
    # Check if the configuration has changed
    if lines_changed:
        print("Configuration has changed. Restarting Avahi daemon...")
        try:
            subprocess.check_call(['systemctl', 'restart', 'avahi-daemon'])
        except subprocess.CalledProcessError as e:
            print(f"Failed to restart Avahi daemon: {e}")
    else:
        print("No changes in configuration. No need to restart Avahi.")
    
    # Clean up - remove the backup file
    try:
        subprocess.check_call(['rm', avahi_conf_bak])
    except subprocess.CalledProcessError as e:
        print(f"Failed to remove backup file: {e}")

if __name__ == "__main__":
    ifaces = get_docker_network_interfaces()
    update_avahi_configuration(ifaces)

