#!/bin/bash

# Start all docker containers
if [ ! -d /data/docker ]; then
  echo "/data/docker does not exist, no containers to start"
  exit 0
fi

for d in /data/docker/*; do
  if [ -f $d/docker-compose.yaml ]; then
    echo starting containers in $d
    cd $d
    docker-compose up -d
  fi
done
