#!/bin/sh
eepmake digipro.txt digipro.eep
eepmake dacplus.txt dacplus.eep 
eepmake digiplus.txt digiplus.eep 
eepmake dacplusadcpro.txt dacplusadcpro.eep 
eepmake dacplusadc.txt dacplusadc.eep
eepmake dac2hd.txt dac2hd.eep
eepmake amp100.txt amp100.eep
eepmake dac2pro.txt dac2pro.eep 
eepmake digi2pro.txt digi2pro.eep 
eepmake beocreate2.txt beocreate2.eep
eepmake digi2standard.txt digi2standard.eep
eepmake amp4.txt amp4.eep
eepmake amp4pro.txt amp4pro.eep
eepmake adc.txt adc.eep
