#!/usr/bin/env bash

mkdir -p "~/.hifiberry"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE=$SCRIPT_DIR/sbuild
ARCH=arm64
DIST=bookworm

while [[ $# -gt 0 ]]; do
    case "$1" in
        --arch)
            ARCH="$2"
            shift 2
            ;;
        --dist)
            DIST="$2"
            shift 2
            ;;
        *)
            echo "Usage: $0 [--arch ARCH] [--dist DIST]"
            exit 1
            ;;
    esac
done

CHROOT_DIR="/srv/chroot/${DIST}-${ARCH}-hifiberry-sbuild"

read -r -d '' INIT_SCRIPT << EOF
#!/usr/bin/env bash

export ARCH="$ARCH"
export DIST="$DIST"

echo "Building for ARCH=\$ARCH DIST=\$DIST"

exec /usr/bin/sbuild --arch="\$ARCH" --dist="\$DIST" --no-clean-source
EOF

echo "$INIT_SCRIPT" > "$OUTPUT_FILE"
chmod +x "$OUTPUT_FILE"

echo "sbuild wrapper complete."
echo ""

if [ -d "$CHROOT_DIR" ]; then
    	echo "CHROOT directory already exists: $CHROOT_DIR"
else
    	echo "Creating CHROOT directory: $CHROOT_DIR"
    	source ${SCRIPT_DIR}/create-chroot --arch $ARCH --dist $DIST
fi
