#!/bin/bash
sudo apt update
sudo apt dist-upgrade
sudo apt install -y  git bc bison flex libssl-dev make screen build-essential devscripts dh-make python3-setuptools  python3-pip ruby-full dh-python python3-all python3-all-dev vim meson
sudo gem install fpm

sudo pip install --break-system-packages build wheel2deb

## Docker for reproducible builds
sudo apt update
sudo apt install -y \
    ca-certificates curl gnupg lsb-release

# Add Docker's official GPG key
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | \
  sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# Add Docker’s official repository
echo \
  "deb [arch=$(dpkg --print-architecture) \
  signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update package index and install
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
