#!/bin/bash

CHANGED=0

IFNAMEEXISTS=`cat /boot/cmdline.txt | grep "net.ifnames=0"`
if [ "$IFNAMEEXISTS" == "" ]; then
  mount -o remount,rw /boot
  echo "Enabling old-style network interface naming"
  sed -i "s/\$/\ net.ifnames=0/g" /boot/cmdline.txt
  CHANGED=1
fi

# Script should run only once
mv $0 $0.done

if [ "$CHANGED" != "0" ]; then
  sync
  reboot
fi
