#!/bin/bash
PART=`/opt/hifiberry/bin/partitions | awk '{print $2}'`
if [ "-f /boot/zImage.bak" ]; then
 echo "No previous release found, aborting..."
 exit 1
fi
mount -o remount,rw /boot
if [ "$PART" == "/dev/mmcblk0p3" ]; then
 echo "root=/dev/mmcblk0p3 rootwait console=tty5 systemd.show_status=0 quiet splash"
 mv /boot/zImage.bak /boot/zImage
 sync
 reboot
fi
if [ "$PART" == "/dev/mmcblk0p2" ]; then
 echo "root=/dev/mmcblk0p2 rootwait console=tty5 systemd.show_status=0 quiet splash"
 mv /boot/zImage.bak /boot/zImage
 sync
 reboot
fi

echo "Unknown backup partition $PART"


