#!/bin/bash

DEVICE=/dev/mmcblk0

# Delete Partition 3
if [ -b ${DEVICE}p3 ]; then
fdisk $DEVICE <<EOT
d
3
w
EOT
partprobe
fi

# Delete Partition 2
if [ -b ${DEVICE}p2 ]; then
fdisk $DEVICE <<EOT
d
2
w
EOT
partprobe
fi

# Create partitions 2 and 3
fdisk $DEVICE <<EOT
n
p
2
65537
2162687
n
p
3
2162688
4259838
w
EOT
partprobe

resize2fs -p /dev/mmcblk0p2
resize2fs -p /dev/mmcblk0p3
if [ "$?" != "0" ]; then
  mkfs -t ext4 /dev/mmcblk0p3
fi
