#!/bin/bash

BASEURL=https://www.hifiberry.com/images
MODE=REBOOT
FORCE=0
DEVMODE=0

for i in "$@"
do
case $i in
    --reboot)
    MODE=REBOOT
    ;;
    --simulate)
    MODE=SIMULATE
    ;;
    --check)
    MODE=CHECK
    ;;
    --force)
    FORCE=1
    ;;
    --development)
    DEVMODE=1
    ;;
esac
done

# Download version file first
cd /tmp
if [ -f listing ]; then
 rm listing
fi
curl $BASEURL/listing >listing 2>/dev/null
if [ "$?" != "0" ]; then
 echo "Could not download listing file, aborting"
fi

# Check version
MYVERSION=`cat /etc/hifiberry.version 2>/dev/null`
if [ "$MYVERSION" == "" ]; then
 MYVERSION=0
fi

. listing

if [ "$DEVMODE" == "1" ]; then
 VERSION=$DEVVERSION
fi

if [ "$VERSION" -le "$MYVERSION" ]; then
 if [ "$MODE" == "CHECK" ]; then
   exit 0
 fi
 if [ "$FORCE" != "1" ]; then
   echo "you are already using the latest version"
   exit 0
 fi
fi

if [ "$MODE" == "CHECK" ]; then
 echo "$VERSION"
 echo
 curl https://hifiberry.com/images/RELEASENOTES
 exit
fi
 
echo "updating from $MYVERSION to $VERSION..."

# find correct version
. /etc/hifiberry.state
if [ "$PIVERSION" == "" ]; then
 PIVERSION=`cat /etc/raspberrypi.version`
fi
UPDATERVAR=UPDATER${PIVERSION}
FILENAME=${!UPDATERVAR}
UPDATER=${BASEURL}/${FILENAME}

# download it
echo "downloading $UPDATER..."
cd /data
curl $UPDATER --progress-bar -o updater.tar.gz 
if [ "$?" != "0" ]; then
 echo "Could not download updater $UPDATER, aborting"
 exit 1
fi

# extract update
if [ "$MODE" == "REBOOT" ]; then
 /opt/hifiberry/bin/extract-update --reboot
elif [ "$MODE" == "SIMULATE" ]; then
 /opt/hifiberry/bin/extract-update --simulate
fi 
