#! /bin/sh

OPTIONS=""

case "$1" in
    start)
	printf "Starting MPD: "
	start-stop-daemon -S -q --exec /usr/bin/echo -- $OPTIONS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping MPD: "
	start-stop-daemon -K -x /usr/bin/echo
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
