#! /bin/sh

# Additional options that are passed to Audiocontrol
OPTIONS=""

case "$1" in
    start)
	printf "Starting audiocontrol: "
	start-stop-daemon -S -q -b --exec /usr/bin/audiocontrol -- $OPTIONS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping audiocontrol: "
	start-stop-daemon -K -q /usr/bin/audiocontrol
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

