context.objects = [
  {
    factory = adapter
    args = {
      factory.name      = "support.node.filter-chain"
      node.name         = "balance-filter"
      node.description  = "Stereo Balance Filter"
      media.class       = "Audio/Sink"
      filter.smart      = true
      filter.smart.name = "balance-filter"
      filter.smart.target = {
        node.name = "alsa_output.*"
      }
      filter.graph      = "/etc/wireplumber/filter-chains/balance-filter-chain.conf"
    }
  }
]
